
/**
 * preview.js
 *
 * Template for post content in general
 */

var h = require('virtual-dom/h');
var svg = require('virtual-dom/virtual-hyperscript/svg');

module.exports = template;

/**
 * Template defines html structure
 *
 * @param   Object  data  From renderer
 * @return  VNode
 */
function template(data) {
	var i18n = data.i18n;

	// TODO: should we make sure they both exist?
	var post = data.post;
	var embed = post.embed;

	var images;
	if (embed.image) {
		images = embed.image.map(function(url) {
			return h('div.m-image', [
				h('img.lazyload', {
					// url is generated by us, no xss filter needed
					src: url + '&size=100'
					// attributes are escaped by vdom as well
					, alt: embed.title + i18n.t('placeholder.image-preview')
					, attributes: {
						'data-srcset': url + '&size=100 100w, ' + url + '&size=200 200w, ' + url + '&size=400 400w'
						, 'data-sizes': 'auto' 
					}
				})
			]);
		});

		images = h('div.m-images', images);
	}

	var title;
	if (post.title) {
		// no need for xss filter, we consider title as pure text
		title = h('h2.m-title', post.title);
	}

	var summary;
	if (post.summary) {
		// no need for xss filter, we consider summary as pure text
		summary = h('p.m-quote', post.summary);
	}

	var item = h('div.m-preview', [
		images
		, h('div.m-meta', [
			title
			, summary
			, h('p.m-author', [
				h('a.m-link', {
					href: '/u/' + post.user
				}, [
					h('span.m-text', post.user_name)
				])
				, h('span', i18n.t('club.posted-on'))
				, h('a.m-link', {
					href: '/c/' + post.club
				}, [
					h('span.m-text', post.club_name)
				])
			])
		])
	]);

	return item;
};